// <auto-generated>
//     GERADO por tools/gerar-interop.py a partir do SDK Inner Acesso 6.0.2.0.
//     Nao edite a mao: a proxima geracao sobrescreve.
//
//     Cada declaracao aqui foi conferida contra a tabela de exportacao da propria
//     EasyInner.dll. Uma funcao que nao esta exportada nao entra.
//
//     As 38 funcoes que a operacao usa moram em EasyInnerNative.cs, escritas a mao e
//     documentadas uma a uma. Este arquivo traz o resto da superficie, para que o produto
//     esteja preparado para leitor de QR, biometria, listas, horarios e as variantes de
//     leitor de proximidade sem depender de uma nova rodada de pesquisa.
// </auto-generated>

using System.Runtime.InteropServices;

namespace Topdata.EasyInner.Interop;

/// <summary>
/// Restante da superficie da <c>EasyInner.dll</c>, gerada do SDK.
/// </summary>
/// <remarks>
/// <para>
/// Declarar nao e usar: nada aqui e chamado pelo produto hoje. Existe para que adicionar
/// um leitor de QR, ligar biometria ou configurar horarios seja trabalho de dias e nao de
/// semanas — e para que ninguem precise deduzir assinatura quando a pressa chegar.
/// </para>
/// <para>
/// Buffers de saida de texto sao <c>byte[]</c> e nao <c>StringBuilder</c>: o analisador
/// recusa StringBuilder em P/Invoke, e o tamanho explicito importa quando estoura-lo
/// significa corromper memoria. Use <see cref="EasyInnerNative.NovoBufferDeCartao"/>.
/// </para>
/// <para>
/// <b>Nada aqui foi executado contra hardware.</b>
/// </para>
/// </remarks>
internal static partial class EasyInnerGerada
{
    private const string Dll = "EasyInner.dll";

    // ---------------------------------------------------------------------------------
    // Biometria
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarTodosUsuariosVerid(int Inner, string SenhaAdm);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarUsuarioVerid(int Inner, string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte CompararDigitalLeitor(int Inner, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte CompararPINVerid(int Inner, string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte CompararTemplateVerid(int Inner, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarAjustesQualidadeBio(int Inner, byte Registro, byte Verificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarAjustesSegurancaBio(int Inner, byte Identificacao, byte Verificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarAjustesSensibilidadeBio(int Inner, byte Ganho, byte Brilho, byte Contraste);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarBio(int Inner, byte HabilitaIdentificacao, byte HabilitaVerificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarCapturaAdaptativaBio(int Inner, byte Capturar, byte Total, byte Tempo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarFiltroBio(int Inner, byte Habilitar);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarRedeVerid(int Inner, byte Envia, byte Recebe, byte BroadCast);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte CriarUsuarioLeitorVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirEntradasMudancaOffLineComBiometria(byte Teclado, byte Leitor1, byte Leitor2, byte Verificacao, byte Identificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirFuncaoDefaultSensorBiometria(byte Funcao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarAjustesBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarDigitalUsuario(int Inner, string Usuario, byte[] Digital1, byte[] Digital2);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarDigitalUsuarioBio(int Inner, int TipoModBio, string Usuario, byte[] Digital1, byte[] Digital2);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarListaUsuariosSemDigitalBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarListaUsuariosSemDigitalBioInnerAcesso(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarListaUsuariosSemDigitalBioVariavel(int Inner, int QtdDigitosSD);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarUsuarioBio(int Inner, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte FazerIdentificacaoBiometricaBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte FazerVerificacaoBiometricaBio(int Inner, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte IncluirUsuarioSemDigitalBio(string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte IncluirUsuarioSemDigitalBioInnerAcesso(string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte IncluirUsuarioVerid(int Inner, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirUsuarioLeitorBio(int Inner, byte Tipo, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte LocalizarPrimeiroUsuarioVerid(int Inner, byte Modo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte LocalizarProximoUsuarioVerid(int Inner, byte Modo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte LocalizarUsuarioVerid(int Inner, byte Modo, byte Digitos, string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte PermitirCadastroInnerBioVerid(byte Permite);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDigitalUsuario(int Inner, byte OnLine, byte[] Digital);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDigitalUsuario(int Inner, byte[] Digital, int TamResposta);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDigitalUsuarioBio(int Inner, byte[] BufferTemplate, int TamanhoReceber);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberListaPacUsuariosBio(int Inner, byte[] ListaUsuarios, int TamanhoBuffer);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberModeloBio(int Inner, byte OnLine, ref int Modelo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberPacoteListaUsuariosBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberQuantidadeUsuariosBio(int Inner, byte OnLine, ref int Quantidade);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberRespostaRequisicaoBio(int Inner, ref int TamResposta);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberTemplateLeitor(int Inner, byte OnLine, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberTemplateLeitorInnerBio(int Inner, byte[] TemplateRecebido, int Tamanho);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberTotalUsuariosVerid(int Inner, ref int Total);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberUsuarioCadastradoBio(int Inner, byte OnLine, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberUsuarioComDigital(byte[] Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberUsuarioVerid(int Inner, byte Modo, ref byte Digitos, byte[] Template, string Cartao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberVersaoBio(int Inner, byte OnLine, ref int VersaoAlta, ref int VersaoBaixa);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarCadastrarUsuarioLeitorInnerBio(int Inner, int TipoModBio, byte Solicitacao, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarEnviarAjustesBio(int Inner, int TipoModBio, byte[] AjustesBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarExcluirTodosUsuariosBio(int Inner, int TipoComBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarExcluirUsuarioBio(int Inner, int TipoComBio, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarIdentificarUsuarioLeitorBio(int Inner, int TipoModBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarListarUsuariosBio(int Inner, int TipoComBio, int NumPacote);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarModeloBio(int Inner, int TipoComBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarQuantidadeUsuariosBio(int Inner, int TipoComBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarReceberTemplateLeitorInnerBio(int Inner, int TipoModBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarUsuarioCadastradoBio(int Inner, int TipoModBio, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarVerificarCadastroUsuarioBio(int Inner, int TipoModBio, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarVerificarDigitalBio(int Inner, int TipoModBio, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarVersaoBio(int Inner, int TipoComBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaCadastrarUsuarioLeitorInnerBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaEnviarAjustesBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaEnviarDigitalUsuarioBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaExcluirTodosUsuariosBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaExcluirUsuarioBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaIdentificarUsuarioLeitorBio(int Inner, byte[] UsuarioIdentificado);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaListarUsuariosBio(int Inner, ref int QtdPacotes, ref int Tamanho);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaModeloBio(int Inner, byte[] ModeloBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaQuantidadeUsuariosBio(int Inner, ref int QtdUsuariosBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaReceberTemplateLeitorInnerBio(int Inner, ref int Tamanho);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaUsuarioCadastradoBio(int Inner, ref int TamanhoReceber);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaVerificarCadastroUsuarioBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaVerificarDigitalBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaVersaoBio(int Inner, byte[] VersaoBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoComparacaoDigitalLeitor(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoComparacaoPINVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoComparacaoTemplateVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoConfiguracaoBio(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoConfiguracaoRedeVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoExclusaoTodosUsuariosVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoExclusaoUsuarioVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoIdentificacaoBiometrica(int Inner, byte OnLine, byte[] Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoInclusaoUsuarioLeitorVerid(int Inner, byte[] Template);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoInclusaoUsuarioVerid(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoInsercaoUsuarioLeitorBio(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ResultadoVerificacaoBiometrica(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarDigitalUsuario(int Inner, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarListaUsuariosBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarListaUsuariosBioVariavel(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarListaUsuariosComDigital(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarModeloBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarQuantidadeUsuariosBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarTemplateLeitor(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarTotalUsuariosVerid(int Inner, byte Modo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarUsuarioCadastradoBio(int Inner, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarVersaoBio(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern void ConfigurarBioVariavel(int Maior);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern void InicializarColetaListaUsuariosBio();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern void SetarBioLight(int Light);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern void SetarBioVariavel(int Maior);


    // ---------------------------------------------------------------------------------
    // Coleta
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberQuantidadeBilhetes(int Inner, int[] QtdeBilhetes);


    // ---------------------------------------------------------------------------------
    // Comunicacao
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern int ConectarModem(int Porta, string Str, int Tom, string Telefone, int Inner);


    // ---------------------------------------------------------------------------------
    // Configuracao
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarBotaoExternoOffline(byte Funcao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeAcura();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeHIDAbaTrack2();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeMotorolaAbaTrack2();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeSmartCard();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeSmartCardAcura();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeWiegand();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarLeitorProximidadeWiegandFacilityCode();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarNivelLFD(byte NivelLFD);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarTimeoutIdentificacao(byte TimeoutIdentificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ConfigurarWiegandDoisLeitores(byte Habilita, byte ExibirMensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirCodigoEmpresa(int Codigo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirConfiguracaoTecladoOnLine(byte Digitos, byte EcoDisplay, byte Tempo, byte PosicaoCursor);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirConfiguracoesFuncoes(byte Funcao, byte Catraca, byte Rele1, byte Rele2, byte Lista, byte Biometria);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirEntradasMudancaOffLine(byte Teclado, byte Leitor1, byte Leitor2, byte Catraca);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirEntradasMudancaOnLine(byte Entrada);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirEventoSensor(byte Sensor, byte Evento, byte Tempo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirFormasPictogramasMillenium(byte Forma);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirFuncaoDefaultLeitoresProximidade(byte Funcao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirLogicaRele(byte Logica);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemApresentacaoEntrada(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemApresentacaoSaida(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemEntradaOffLine(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemFuncaoOffLine(string Mensagem, byte Funcao, byte Habilitada);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemPadraoMudancaOffLine(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemPadraoMudancaOnLine(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemPadraoOffLine(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirMensagemSaidaOffLine(byte ExibirData, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirNivelAcesso(byte Nivel);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirNumeroCartaoMaster(string Master);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirPorcentagemRevista(byte Porcentagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirSensorPortaOffline(byte Logica);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte HabilitarScoreFuncoes(int Funcao, byte Score);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte HabilitarScoreMensagemOffLine(int Inner, byte Tipo, byte Habilitar);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RequisitarHabilitarIdentificacaoVerificacao(int Inner, int TipoModBio, int Identificacao, int Verificacao);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RespostaHabilitarIdentificacaoVerificacao(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte UtilizarSenhaAcesso(byte Utiliza);


    // ---------------------------------------------------------------------------------
    // Envio
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarBufferEventosMudancaAuto(int NumInner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarConfiguracoesFuncoes(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarMensagemImpressora00(int Inner, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarMensagemImpressoraFF(int Inner, string Mensagem);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarMensagensOffLine(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarSinalizacao(int Inner, byte TipoSinalizacao, byte ModoSinalizacao, byte Terminal);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern int EnviarStringInicializacaoModem(string Str);


    // ---------------------------------------------------------------------------------
    // Horarios e listas
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarHorariosAcesso(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarHorariosSirene(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarListaAcesso(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DefinirTipoListaAcesso(byte Tipo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarHorarioVerao(int Inner, byte DiaInicio, byte MesInicio, byte AnoInicio, byte HoraInicio, byte MinutoInicio, byte DiaFim, byte MesFim, byte AnoFim, byte HoraFim, byte MinutoFim);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarHorariosAcesso(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarHorariosSirene(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EnviarListaAcesso(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirHorarioAcesso(byte Horario, byte DiaSemana, byte FaixaDia, byte Hora, byte Minuto);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirHorarioMudancaEntrada(byte Hora1, byte Minuto1, byte Hora2, byte Minuto2, byte Hora3, byte Minuto3);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirHorarioMudancaSaida(byte Hora1, byte Minuto1, byte Hora2, byte Minuto2, byte Hora3, byte Minuto3);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirHorarioSirene(byte Hora, byte Minuto, byte Segunda, byte Terca, byte Quarta, byte Quinta, byte Sexta, byte Sabado, byte DomingoFeriado);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirUsuarioListaAcesso(string Cartao, byte Horario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberUsuarioLista(int Inner, byte[] Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte SolicitarExclusaoUsuario(int Inner, string Usuario);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte UsuarioFoiEnviado(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte UsuarioFoiExcluido(int Inner, byte OnLine);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern int TemProximoUsuario();


    // ---------------------------------------------------------------------------------
    // Leitura
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberConfiguracoesInner(int Inner, byte[] ConfiguracoesInner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDadosOnLine_ComLetras(int Inner, ref byte Origem, ref byte Complemento, byte[] Cartao, ref byte Dia, ref byte Mes, ref byte Ano, ref byte Hora, ref byte Minuto, ref byte Segundo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDadosOnLine_QRCodeComLetras(int Inner, ref byte Origem, ref byte Complemento, byte[] Cartao, ref byte Dia, ref byte Mes, ref byte Ano, ref byte Hora, ref byte Minuto, ref byte Segundo);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberDataHoraDadosOnLine(byte Recebe);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberVersaoFirmware6xx(int Inner, ref byte Linha, ref short Variacao, ref byte VersaoAlta, ref byte VersaoBaixa, ref byte VersaoSufixo, ref byte InnerAcessoBio, ref byte TipoModBio);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ReceberVersaoFirmware6xx_ComComplementar(int Inner, ref byte Linha, ref short Variacao, ref byte VersaoAlta, ref byte VersaoBaixa, ref byte VersaoSufixo, ref byte InnerAcessoBio, ref byte TipoModBio, ref byte ComplementarVersaoSuperior, ref byte ComplementarVersaoInferior, ref byte TipoDeOperacao);


    // ---------------------------------------------------------------------------------
    // Outros
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ApagarMensagensOffLine(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte AvisarQuandoMemoriaCheia(byte Avisa);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte CartaoMasterLiberaAcesso(byte Libera);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarBipCatraca(byte Desabilita);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarBipColetor(byte Desabilita);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarBloqueioCatracaMicroSwitch(byte Desabilita);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarRele1(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarRele2(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesabilitarWebServer(byte Desabilita);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DevolverCartao(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte EngolirCartao(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte InserirQuantidadeDigitoVariavel(byte Digito);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte LerSensoresInner(int Inner, ref byte StatusSensor1, ref byte StatusSensor2, ref byte StatusSensor3);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ManterRele1Acionado(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte ManterRele2Acionado(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte RegistrarAcessoNegado(byte TipoRegistro);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern int LerByteModem();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern int TemProximoPacote();

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern void SetarInnerOld(int Inner, int Old);


    // ---------------------------------------------------------------------------------
    // Sinalizacao
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte DesligarBipIntermitente(int Inner);

    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte LigarBipIntermitente(int Inner);


    // ---------------------------------------------------------------------------------
    // Tempo real
    // ---------------------------------------------------------------------------------
    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]
    internal static extern byte AcionarRele1(int Inner);

}
