<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Integration.Tests</AssemblyName>
    <RootNamespace>Integration.Tests</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Access.Domain/Access.Domain.csproj" />
    <ProjectReference Include="../../src/Access.Infrastructure.SQLite/Access.Infrastructure.SQLite.csproj" />
    <!-- Referência só para garantir que o executável exista quando o teste de queda rodar. -->
    <ProjectReference Include="../CrashProbe/CrashProbe.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
