#!/usr/bin/env python3
"""
Gera as declaracoes P/Invoke da EasyInner.dll a partir dos fatos do SDK.

POR QUE GERAR, E NAO DIGITAR
    Sao ~190 declaracoes. Um tipo de parametro trocado numa delas nao da excecao: da
    corrupcao de memoria, possivelmente horas depois, possivelmente no meio de um evento.
    Transcricao manual desse volume erra. Geracao mecanica, conferida contra a tabela de
    exportacao do proprio binario, nao.

O QUE E EXTRAIDO, E O QUE NAO E
    Extrai-se apenas o contrato da ABI: nome do simbolo, tipo de retorno, tipos e nomes dos
    parametros. E a mesma informacao que um arquivo de cabecalho carregaria, e e para isso
    que o SDK existe.

    NAO se extrai o codigo do exemplo: nem os comentarios, nem os metodos auxiliares, nem a
    logica. O cabecalho do exemplo diz que ele nao deve ser incluso em aplicacao comercial,
    e nao esta.

USO
    Extraia o SDK com innoextract e rode:
        python3 tools/gerar-interop.py <pasta-do-sdk> <saida.cs>
"""
import re
import sys
from pathlib import Path

CABECALHO = '''// <auto-generated>
//     GERADO por tools/gerar-interop.py a partir do SDK Inner Acesso 6.0.2.0.
//     Nao edite a mao: a proxima geracao sobrescreve.
//
//     Cada declaracao aqui foi conferida contra a tabela de exportacao da propria
//     EasyInner.dll. Uma funcao que nao esta exportada nao entra.
//
//     As 38 funcoes que a operacao usa moram em EasyInnerNative.cs, escritas a mao e
//     documentadas uma a uma. Este arquivo traz o resto da superficie, para que o produto
//     esteja preparado para leitor de QR, biometria, listas, horarios e as variantes de
//     leitor de proximidade sem depender de uma nova rodada de pesquisa.
// </auto-generated>

using System.Runtime.InteropServices;

namespace Topdata.EasyInner.Interop;

/// <summary>
/// Restante da superficie da <c>EasyInner.dll</c>, gerada do SDK.
/// </summary>
/// <remarks>
/// <para>
/// Declarar nao e usar: nada aqui e chamado pelo produto hoje. Existe para que adicionar
/// um leitor de QR, ligar biometria ou configurar horarios seja trabalho de dias e nao de
/// semanas — e para que ninguem precise deduzir assinatura quando a pressa chegar.
/// </para>
/// <para>
/// Buffers de saida de texto sao <c>byte[]</c> e nao <c>StringBuilder</c>: o analisador
/// recusa StringBuilder em P/Invoke, e o tamanho explicito importa quando estoura-lo
/// significa corromper memoria. Use <see cref="EasyInnerNative.NovoBufferDeCartao"/>.
/// </para>
/// <para>
/// <b>Nada aqui foi executado contra hardware.</b>
/// </para>
/// </remarks>
internal static partial class EasyInnerGerada
{
    private const string Dll = "EasyInner.dll";
'''


def categoria(nome: str) -> str:
    for prefixo, rotulo in [
        ("Bio", "Biometria"), ("Verid", "Biometria"), ("Digital", "Biometria"),
        ("Template", "Biometria"), ("Facial", "Facial"),
        ("Urna", "Urna"), ("Bilhete", "Coleta"),
        ("Liberar", "Tempo real"), ("Acionar", "Tempo real"),
        ("Ligar", "Sinalizacao"), ("Desligar", "Sinalizacao"),
        ("Horario", "Horarios e listas"), ("Lista", "Horarios e listas"),
        ("Usuario", "Horarios e listas"),
        ("Receber", "Leitura"), ("Enviar", "Envio"),
        ("Configurar", "Configuracao"), ("Definir", "Configuracao"),
        ("Habilita", "Configuracao"), ("Utilizar", "Configuracao"),
        ("Abrir", "Comunicacao"), ("Fechar", "Comunicacao"),
        ("Ping", "Comunicacao"), ("Conectar", "Comunicacao"),
    ]:
        if prefixo in nome:
            return rotulo
    return "Outros"


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    pasta, saida = Path(sys.argv[1]), Path(sys.argv[2])

    fonte = pasta / "app/Exemplos/CSharp/LabEasyInner/Fontes/COM/EasyInner.cs"
    if not fonte.exists():
        print(f"ERRO: nao achei {fonte}", file=sys.stderr)
        return 1

    exportadas = exports_da_dll(pasta / "app/DLLs/EasyInner.dll")
    print(f"a DLL exporta {len(exportadas)} simbolos")

    texto = fonte.read_text(encoding="latin1")
    manuais = nomes_ja_declarados()

    encontradas, geradas, puladas = 0, [], []

    for m in re.finditer(r"static extern ([\w\[\]]+)\s+(\w+)\(([^)]*)\);", texto):
        retorno, nome, params = m.group(1), m.group(2), " ".join(m.group(3).split())
        encontradas += 1

        if nome not in exportadas:
            puladas.append((nome, "nao exportada pela DLL"))
            continue
        if nome in manuais:
            continue

        params_cs = traduzir(params)
        if params_cs is None:
            puladas.append((nome, f"tipo de parametro nao mapeado: {params}"))
            continue

        geradas.append((categoria(nome), retorno, nome, params_cs))

    escrever(saida, geradas)

    print(f"declaracoes no exemplo : {encontradas}")
    print(f"ja escritas a mao      : {len(manuais)}")
    print(f"geradas                : {len(geradas)}")
    print(f"puladas                : {len(puladas)}")
    for nome, motivo in puladas:
        print(f"    {nome}: {motivo}")
    return 0


def traduzir(params: str):
    """Traduz a lista de parametros. Devolve None se houver tipo nao previsto."""
    if not params:
        return ""

    permitidos = {"int", "byte", "ref byte", "ref int", "ref short", "string", "byte[]", "int[]"}
    saida = []

    for p in params.split(","):
        toks = p.strip().split()
        if len(toks) < 2:
            return None

        tipo, nome = " ".join(toks[:-1]), toks[-1]

        # Buffer de saida de texto: byte[] explicito, nunca StringBuilder.
        if tipo == "StringBuilder":
            tipo = "byte[]"

        if tipo not in permitidos:
            return None

        saida.append(f"{tipo} {nome}")

    return ", ".join(saida)


def nomes_ja_declarados() -> set:
    manual = Path(__file__).resolve().parent.parent / "src/Topdata.EasyInner.Interop/EasyInnerNative.cs"
    return set(re.findall(r"internal static extern [\w\[\]]+ (\w+)\(", manual.read_text(encoding="utf-8")))


def exports_da_dll(caminho: Path) -> set:
    """Le a tabela de exportacao do PE. O binario e a fonte da verdade."""
    import struct

    d = caminho.read_bytes()
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    nsec = struct.unpack_from("<H", d, pe + 6)[0]
    opt = pe + 24
    magic = struct.unpack_from("<H", d, opt)[0]
    erva = struct.unpack_from("<I", d, opt + (96 if magic == 0x10B else 112))[0]

    secoes = []
    inicio = opt + struct.unpack_from("<H", d, pe + 20)[0]
    for i in range(nsec):
        o = inicio + i * 40
        vsz, va, rsz, ra = struct.unpack_from("<IIII", d, o + 8)
        secoes.append((va, max(vsz, rsz), ra))

    def offset(rva):
        for va, tam, ra in secoes:
            if va <= rva < va + tam:
                return ra + (rva - va)
        return None

    eo = offset(erva)
    qtd = struct.unpack_from("<I", d, eo + 24)[0]
    tabela = offset(struct.unpack_from("<I", d, eo + 32)[0])

    nomes = set()
    for i in range(qtd):
        p = offset(struct.unpack_from("<I", d, tabela + i * 4)[0])
        nomes.add(d[p:d.index(b"\0", p)].decode("latin1"))
    return nomes


def escrever(saida: Path, geradas: list) -> None:
    linhas = [CABECALHO]

    for cat in sorted({c for c, _, _, _ in geradas}):
        linhas.append(f"\n    // {'-' * 81}\n    // {cat}\n    // {'-' * 81}\n")
        for _, retorno, nome, params in sorted(g for g in geradas if g[0] == cat):
            linhas.append(
                f'    [DllImport(Dll, CallingConvention = CallingConvention.Winapi, ExactSpelling = true)]\n'
                f"    internal static extern {retorno} {nome}({params});\n\n"
            )

    linhas.append("}\n")
    saida.write_text("".join(linhas), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
